// Converts the four Uncrustables YAML model files into js/data.generated.js
// Run: npm run gen
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { load } from 'js-yaml';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (f) => load(fs.readFileSync(path.join(root, f), 'utf8'));

const bau = read('uncrustables_bau_graph_cost_enriched.yaml');
const overlay = read('uncrustables_events_alerts_overlay.yaml');
const runtime = read('uncrustables_simulation_runtime_contract.yaml');
const decision = read('uncrustables_intervention_decision_layer.yaml');

const out = `// GENERATED by scripts/build-data.mjs — do not edit by hand.
// Source: uncrustables_*.yaml
export const BAU_GRAPH = ${JSON.stringify({ nodes: bau.nodes, relationships: bau.relationships }, null, 1)};

export const ALERT_OVERLAY = ${JSON.stringify(overlay, null, 1)};

export const RUNTIME_CONTRACT = ${JSON.stringify(runtime, null, 1)};

export const DECISION_LAYER = ${JSON.stringify(decision, null, 1)};
`;

fs.mkdirSync(path.join(root, 'js'), { recursive: true });
fs.writeFileSync(path.join(root, 'js', 'data.generated.js'), out);
console.log('Wrote js/data.generated.js',
  '| nodes:', bau.nodes.length,
  '| relationships:', bau.relationships.length,
  '| events:', overlay.events.length,
  '| playbook event types:', decision.intervention_playbook.length,
  '| cost components:', decision.cost_rollup_model.cost_components.length);
